branch-defaults:
  master:
    environment: sample-node-app-dev
    group_suffix: null
global:
  application_name: sample-node-app
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dev
  repository: null
  sc: git
  workspace_type: Application
